### PR TITLE
Keep track of bounding boxes

### PR DESCRIPTION
**Pull request by j6k4m8**
2 of 2 from Pyrtri2 branch, thanks @Raphtor!

### CODE REVIEW

**Comment by j6k4m8** [comment]
I had two thoughts on this one —

- I think we also want to keep track of min extents, since objects can go in the negative XYZ direction too
- I don't know if it's super important to keep track of ALL max bboxes, since we can just keep track of the current largest. But if you want to keep track of them all (in case we delete a layer, perhaps?) it might make sense to attach them to `Figure#_layer_lookup` so that we can remove bboxes when items are removed from the scene (and keep it in sync with the current viewport contents)

**Comment by Raphtor** [comment]
I don't think it's important to track min extents, because even if coordinates are negative, the camera would be placed past the max of the negative coordinates, which should still be a valid viewpoint. I agree on the second one point. Keying by object id or something would be easy.

**Review by Raphtor — DISMISSED** [review]

**Comment by j6k4m8** [comment]
@Raphtor my thought was that we could use those bounding boxes to determine a "view all" camera position.

If all of the coords are, for example, in the range (1000, 2000), then showing the origin isn't useful.

**Comment by Raphtor** [comment]
I was pointing the camera at the mean of the coordinates so it _shouldn't_ care where they are centered. I can see a couple potential issues with this:

1. If there is a number of outlier points that bias the mean (maybe median or something else makes sense here too)
2. The "best" viewpoint may not always be a ray passing through the max coordinates to the mean. This is kind of arbitrary so not sure if theres a better way

Either way, I think this is good to merge in for now. We can change if needed later

**Review by Raphtor — APPROVED** [review]

**Pull request merged**
